1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

In [4]:
a = np.zeros(10, int)
a[4] = 1

In [5]:
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2. Create a vector with values ranging from 10 to 49.

In [7]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import random
a = np.random.randint(0,9,(3,3))
a

array([[2, 6, 6],
       [5, 5, 2],
       [8, 2, 4]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4], dtype=int64),)

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [19]:
a = np.random.rand(10,10)
print('Max is',a.max())
print('Min is',a.min())

Max is 0.9944293631272203
Min is 0.008695995516262545


6. Create a random vector of size 30 and find the mean value.

In [23]:
a = np.random.rand(30)
print(a)
print('\n\nMean of the vector is: ', a.mean())

[0.98170063 0.27069898 0.23298716 0.73661112 0.9099851  0.83925286
 0.40908913 0.09524362 0.53865661 0.21792165 0.18070526 0.576577
 0.08949873 0.64038782 0.39257449 0.53399106 0.9414138  0.94014293
 0.62786415 0.06863846 0.37024111 0.56450432 0.82339589 0.29397219
 0.15783606 0.67693593 0.55518339 0.59589748 0.09038075 0.21017645]


Mean of the vector is:  0.4854154713992981
